services:
  postgres:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost -p ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT} --reload
    env_file: .env
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      PYTHONPATH: /code
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker_order:
    build: .
    env_file: .env
    command: python -m app.workers.order_worker
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      PYTHONPATH: /code
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker_stock:
    build: .
    env_file: .env
    command: python -m app.workers.stock_worker
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      PYTHONPATH: /code
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker_notify:
    build: .
    env_file: .env
    command: python -m app.workers.notify_worker
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      PYTHONPATH: /code
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker_payment:
    build: .
    env_file: .env
    command: python -m app.workers.payment_worker
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      PYTHONPATH: /code
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: